stages:
- build_production
- build_uat
- test

image:
    name: docker/compose:latest
services:
- docker:dind
before_script:
- docker version
- docker-compose version

build_uat:
    stage: build
    script:
    - docker build -t nodejs .
    - docker-compose up -d
test:
    stage: test
    script :
    - docker build -t nodejs .
    - docker-compose up -d
    - sleep 5
only:
    - master
    when: manual

build_production:
    stage: build
    script:
    - docker build -t nodejs .
    - docker-compose up -d
test:
    stage: test
    script :
    - docker build -t nodejs .
    - docker-compose up -d
    - sleep 5
only:
    - master
    when: manual